---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCNCfs12ffWhY1cq/bHOBILh4CsWwaPaqE9Nkv6ZBm4AvQca1FsliNWjR9d9og77vWTV6Nu83OU3ailEIOFjwKG3hlWzNt8VLWp6XSvzWTQktIxvYVAGkr1x1DW9ozWNh4BW+2o4vE9ee7H2jVh74r1VGNOc4cnNS2XPvBqjxnXdrEWZf0ta9RrDSA2fxS0KcPr3R1aRrzdBpKnrcmtriIRWvw1NP/EkqAYyGfe3iYlh+yn6dZWEc+gbZ12GT0YwlTcJpzLn2BIlSVN5P+8PljHWoIFdu8aNU7K4YgURAWW42UTfCDwzPaKm8HapxIdjdmLFQgVUhEErKdSC2q4v5zK6cUb2hSPB7btoAQg3cZJ+NzeT1aPd9oNuf/DngJqQejROO03yrc+5dy6IW2y24RFNlYKF0t6eYXZykzglIobKri2Ixh4V3ujYkeb5fAlPg3DWNpP+sMaLEF7BxMQsPX+M2E7b5POH7ojvK6WubcJfn8rNRvmcb2tayk7CkxYvwNTbPIGYm9ZgpjbJuG7dB9WE2+JvmzuYZFrKMW3D6sbvYzH+NVudRTHpxjMP2k+ZFnf7eAUkhSTmQQ3KUejtkgy7u+CIZTQDeJDUo75H42MRurCI3Zt7FB1cI92G+lx9m2J8YGsrF557vMo7L/SMdeW8FYDtvgGiQqgRp+KUFFMNQaNRZ600NpDT7kuQWmzkym8G+I/dqu5SHKNiM/V+7Gmjvny0w7rmOX9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
